# Generated by Django 5.2.4 on 2025-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_remove_product_category_bucket_bucketproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("announcement_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("was_announced", models.BooleanField(default=False)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="sales", to="marketplace.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="sales", to="marketplace.product"
                    ),
                ),
            ],
        ),
    ]
